name: Snapshot-Release

on: workflow_dispatch

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - run: ./gradlew clean publish --warn --stacktrace
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.GPG_SIGNING_KEY}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.GPG_SIGNING_PASSPHRASE}}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_PASSWORD}}